apiVersion: v1
kind: Service
metadata:
  name: board-backend-svc
  namespace: board
spec:
  type: ClusterIP
  selector:
    app: board-backend
  ports:
    - port: 8080        # 서비스가 노출하는 포트
      targetPort: 8080  # 컨테이너 포트
