apiVersion: v1
kind: Service
metadata:
  name: board-frontend-svc
  namespace: board
spec:
  type: ClusterIP
  selector:
    app: board-frontend
  ports:
    - port: 80        # 서비스 포트
      targetPort: 80  # 컨테이너 포트
